 
#declare pg125378_obj = union {
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-5.637, -0.351, -1.699> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.215, -0.448, -1.092> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.159, -1.440, 0.055> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-5.095, -2.402, 0.213> }
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-6.082, -2.472, -0.719> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-5.993, -1.815, -1.998> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-7.481, -2.291, -2.151> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-7.296, -3.004, -0.834> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.035, -1.242, 0.994> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-5.112, -3.273, 1.238> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-8.024, -3.722, -0.168> }
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-8.455, -1.211, -2.083> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-5.647, 0.254, -2.619> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.251, -3.255, 2.105> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-6.077, -4.196, 1.314> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-6.014, -4.775, 2.067> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.592, -1.112, 1.550> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.520, -1.544, -0.432> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.924, -0.765, 2.543> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-8.564, -0.346, -3.115> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-7.877, -0.424, -4.121> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-9.580, 0.761, -3.006> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-10.311, 0.603, -1.779> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-11.342, 1.478, -1.406> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-12.015, 1.242, -0.203> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-13.052, 2.081, 0.213> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-13.424, 3.171, -0.577> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-12.756, 3.415, -1.780> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-11.718, 2.574, -2.195> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-6.342, 0.081, -0.971> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.500, -0.766, -1.867> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.913, 0.552, -0.742> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-5.301, -2.336, -2.682> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-7.654, -2.991, -2.985> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.089, -2.084, 1.673> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.754, -1.317, 0.609> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.277, -1.019, 2.033> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-9.036, -1.125, -1.270> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-9.047, 1.724, -3.017> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-10.261, 0.694, -3.869> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-11.727, 0.395, 0.413> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-13.568, 1.887, 1.149> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-14.230, 3.826, -0.259> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-13.046, 4.262, -2.395> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-11.224, 2.797, -3.132> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <10.471, 1.895, 1.803> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <11.289, 0.739, 1.392> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <10.696, -0.267, 0.732> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.083, 0.536, 0.889> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <6.253, 1.648, 1.058> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <6.788, 2.853, 1.519> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.155, 2.949, 1.791> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.990, 1.864, 1.512> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.474, 0.695, 0.947> }
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <9.369, -0.298, 0.450> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.873, -1.364, -0.415> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.059, -0.974, -1.669> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <9.535, -1.390, -1.812> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <10.968, 2.861, 2.360> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <12.738, 0.714, 1.698> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <13.418, -0.237, 1.339> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <13.294, 1.732, 2.365> }
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <4.872, 1.565, 0.764> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <3.877, 1.280, 1.816> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <2.580, 0.984, 1.027> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <3.130, 0.269, -0.226> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <4.381, 1.116, -0.555> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <6.516, -0.720, 0.680> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <6.585, -1.582, 1.828> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <1.548, 0.136, 1.815> }
object {Atom_F scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <5.994, 3.905, 1.703> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <11.304, -1.106, 0.393> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.558, 3.864, 2.211> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.745, -2.373, 0.006> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.288, -1.695, -1.983> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.829, 0.095, -1.799> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <9.704, -2.367, -2.292> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <10.225, -0.575, -2.081> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <14.228, 1.628, 2.516> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <4.196, 0.395, 2.384> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <3.762, 2.131, 2.506> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <2.124, 1.941, 0.718> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <3.445, -0.755, 0.036> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <2.405, 0.222, -1.055> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <5.121, 0.547, -1.141> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <4.097, 2.017, -1.122> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <6.036, -1.152, 2.679> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.625, -1.763, 2.140> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <6.123, -2.544, 1.560> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <2.016, -0.814, 2.117> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <1.249, 0.680, 2.727> }
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.364, -0.143, 0.971> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.144, 0.780, 0.718> }
cylinder { <0.36, -0.14, 0.97>, <-0.14, 0.78, 0.72>, BOND_RADIUS texture {White_Bond} } 
cylinder { <1.55, 0.14, 1.81>, <0.36, -0.14, 0.97>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.59, -1.11, 1.55>, <0.36, -0.14, 0.97>, BOND_RADIUS texture {White_Bond} } 
cylinder { <1.55, 0.14, 1.81>, <1.25, 0.68, 2.73>, BOND_RADIUS texture {White_Bond} } 
cylinder { <1.55, 0.14, 1.81>, <2.02, -0.81, 2.12>, BOND_RADIUS texture {White_Bond} } 
cylinder { <6.58, -1.58, 1.83>, <6.12, -2.54, 1.56>, BOND_RADIUS texture {White_Bond} } 
cylinder { <6.58, -1.58, 1.83>, <7.62, -1.76, 2.14>, BOND_RADIUS texture {White_Bond} } 
cylinder { <6.58, -1.58, 1.83>, <6.04, -1.15, 2.68>, BOND_RADIUS texture {White_Bond} } 
cylinder { <4.38, 1.12, -0.56>, <4.10, 2.02, -1.12>, BOND_RADIUS texture {White_Bond} } 
cylinder { <4.38, 1.12, -0.56>, <5.12, 0.55, -1.14>, BOND_RADIUS texture {White_Bond} } 
cylinder { <3.13, 0.27, -0.23>, <2.40, 0.22, -1.06>, BOND_RADIUS texture {White_Bond} } 
cylinder { <3.13, 0.27, -0.23>, <3.44, -0.75, 0.04>, BOND_RADIUS texture {White_Bond} } 
cylinder { <2.58, 0.98, 1.03>, <2.12, 1.94, 0.72>, BOND_RADIUS texture {White_Bond} } 
cylinder { <3.88, 1.28, 1.82>, <3.76, 2.13, 2.51>, BOND_RADIUS texture {White_Bond} } 
cylinder { <3.88, 1.28, 1.82>, <4.20, 0.40, 2.38>, BOND_RADIUS texture {White_Bond} } 
cylinder { <13.29, 1.73, 2.36>, <14.23, 1.63, 2.52>, BOND_RADIUS texture {White_Bond} } 
cylinder { <9.53, -1.39, -1.81>, <10.22, -0.57, -2.08>, BOND_RADIUS texture {White_Bond} } 
cylinder { <9.53, -1.39, -1.81>, <9.70, -2.37, -2.29>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.06, -0.97, -1.67>, <7.83, 0.10, -1.80>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.06, -0.97, -1.67>, <7.29, -1.69, -1.98>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.87, -1.36, -0.42>, <8.74, -2.37, 0.01>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.15, 2.95, 1.79>, <8.56, 3.86, 2.21>, BOND_RADIUS texture {White_Bond} } 
cylinder { <10.70, -0.27, 0.73>, <11.30, -1.11, 0.39>, BOND_RADIUS texture {White_Bond} } 
cylinder { <6.79, 2.85, 1.52>, <5.99, 3.91, 1.70>, BOND_RADIUS texture {White_Bond} } 
cylinder { <2.58, 0.98, 1.03>, <1.55, 0.14, 1.81>, BOND_RADIUS texture {White_Bond} } 
cylinder { <6.52, -0.72, 0.68>, <6.58, -1.58, 1.83>, BOND_RADIUS texture {White_Bond} } 
cylinder { <7.08, 0.54, 0.89>, <6.52, -0.72, 0.68>, BOND_RADIUS texture {White_Bond} } 
cylinder { <3.13, 0.27, -0.23>, <4.38, 1.12, -0.56>, BOND_RADIUS texture {White_Bond} } 
cylinder { <4.87, 1.57, 0.76>, <4.38, 1.12, -0.56>, BOND_RADIUS texture {White_Bond} } 
cylinder { <2.58, 0.98, 1.03>, <3.13, 0.27, -0.23>, BOND_RADIUS texture {White_Bond} } 
cylinder { <3.88, 1.28, 1.82>, <2.58, 0.98, 1.03>, BOND_RADIUS texture {White_Bond} } 
cylinder { <4.87, 1.57, 0.76>, <3.88, 1.28, 1.82>, BOND_RADIUS texture {White_Bond} } 
cylinder { <6.25, 1.65, 1.06>, <4.87, 1.57, 0.76>, BOND_RADIUS texture {White_Bond} } 
cylinder { <12.74, 0.71, 1.70>, <13.29, 1.73, 2.36>, BOND_RADIUS texture {White_Bond} } 
cylinder { <12.74, 0.71, 1.70>, <13.42, -0.24, 1.34>, BOND_RADIUS texture {White_Bond} } 
cylinder { <11.29, 0.74, 1.39>, <12.74, 0.71, 1.70>, BOND_RADIUS texture {White_Bond} } 
cylinder { <10.47, 1.90, 1.80>, <10.97, 2.86, 2.36>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.06, -0.97, -1.67>, <9.53, -1.39, -1.81>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.87, -1.36, -0.42>, <9.53, -1.39, -1.81>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.87, -1.36, -0.42>, <8.06, -0.97, -1.67>, BOND_RADIUS texture {White_Bond} } 
cylinder { <9.37, -0.30, 0.45>, <8.87, -1.36, -0.42>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.47, 0.70, 0.95>, <9.37, -0.30, 0.45>, BOND_RADIUS texture {White_Bond} } 
cylinder { <10.70, -0.27, 0.73>, <9.37, -0.30, 0.45>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.99, 1.86, 1.51>, <8.47, 0.70, 0.95>, BOND_RADIUS texture {White_Bond} } 
cylinder { <7.08, 0.54, 0.89>, <8.47, 0.70, 0.95>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.15, 2.95, 1.79>, <8.99, 1.86, 1.51>, BOND_RADIUS texture {White_Bond} } 
cylinder { <10.47, 1.90, 1.80>, <8.99, 1.86, 1.51>, BOND_RADIUS texture {White_Bond} } 
cylinder { <6.79, 2.85, 1.52>, <8.15, 2.95, 1.79>, BOND_RADIUS texture {White_Bond} } 
cylinder { <6.25, 1.65, 1.06>, <6.79, 2.85, 1.52>, BOND_RADIUS texture {White_Bond} } 
cylinder { <7.08, 0.54, 0.89>, <6.25, 1.65, 1.06>, BOND_RADIUS texture {White_Bond} } 
cylinder { <11.29, 0.74, 1.39>, <10.70, -0.27, 0.73>, BOND_RADIUS texture {White_Bond} } 
cylinder { <10.47, 1.90, 1.80>, <11.29, 0.74, 1.39>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-11.72, 2.57, -2.20>, <-11.22, 2.80, -3.13>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-12.76, 3.42, -1.78>, <-13.05, 4.26, -2.40>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-13.42, 3.17, -0.58>, <-14.23, 3.83, -0.26>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-13.05, 2.08, 0.21>, <-13.57, 1.89, 1.15>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-12.02, 1.24, -0.20>, <-11.73, 0.40, 0.41>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-9.58, 0.76, -3.01>, <-10.26, 0.69, -3.87>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-9.58, 0.76, -3.01>, <-9.05, 1.72, -3.02>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-8.46, -1.21, -2.08>, <-9.04, -1.12, -1.27>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.04, -1.24, 0.99>, <-3.28, -1.02, 2.03>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-1.52, -1.54, -0.43>, <-1.75, -1.32, 0.61>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.59, -1.11, 1.55>, <-1.75, -1.32, 0.61>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.04, -1.24, 0.99>, <-1.75, -1.32, 0.61>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.59, -1.11, 1.55>, <-0.09, -2.08, 1.67>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-7.48, -2.29, -2.15>, <-7.65, -2.99, -2.99>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.99, -1.81, -2.00>, <-5.30, -2.34, -2.68>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-4.22, -0.45, -1.09>, <-3.91, 0.55, -0.74>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-4.22, -0.45, -1.09>, <-3.50, -0.77, -1.87>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.64, -0.35, -1.70>, <-6.34, 0.08, -0.97>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-12.76, 3.42, -1.78>, <-11.72, 2.57, -2.20>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-11.34, 1.48, -1.41>, <-11.72, 2.57, -2.20>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-13.42, 3.17, -0.58>, <-12.76, 3.42, -1.78>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-13.05, 2.08, 0.21>, <-13.42, 3.17, -0.58>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-12.02, 1.24, -0.20>, <-13.05, 2.08, 0.21>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-11.34, 1.48, -1.41>, <-12.02, 1.24, -0.20>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-10.31, 0.60, -1.78>, <-11.34, 1.48, -1.41>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-9.58, 0.76, -3.01>, <-10.31, 0.60, -1.78>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-8.56, -0.35, -3.12>, <-9.58, 0.76, -3.01>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-8.56, -0.35, -3.12>, <-7.88, -0.42, -4.12>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-8.46, -1.21, -2.08>, <-8.56, -0.35, -3.12>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.59, -1.11, 1.55>, <-0.92, -0.76, 2.54>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-6.08, -4.20, 1.31>, <-6.01, -4.77, 2.07>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.11, -3.27, 1.24>, <-6.08, -4.20, 1.31>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.11, -3.27, 1.24>, <-4.25, -3.25, 2.10>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.64, -0.35, -1.70>, <-5.65, 0.25, -2.62>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-7.48, -2.29, -2.15>, <-8.46, -1.21, -2.08>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-7.30, -3.00, -0.83>, <-8.02, -3.72, -0.17>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.10, -2.40, 0.21>, <-5.11, -3.27, 1.24>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-4.16, -1.44, 0.05>, <-3.04, -1.24, 0.99>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-7.48, -2.29, -2.15>, <-7.30, -3.00, -0.83>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-6.08, -2.47, -0.72>, <-7.30, -3.00, -0.83>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.99, -1.81, -2.00>, <-7.48, -2.29, -2.15>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-6.08, -2.47, -0.72>, <-5.99, -1.81, -2.00>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.64, -0.35, -1.70>, <-5.99, -1.81, -2.00>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.10, -2.40, 0.21>, <-6.08, -2.47, -0.72>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-4.16, -1.44, 0.05>, <-5.10, -2.40, 0.21>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-4.22, -0.45, -1.09>, <-4.16, -1.44, 0.05>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.64, -0.35, -1.70>, <-4.22, -0.45, -1.09>, BOND_RADIUS texture {White_Bond} } 
}

#declare pg125378 = object {
	object { pg125378_obj } 
	rotate <0,0,90>
	translate <0,6,0>
     } 


