//----- Defined Textures for Helmet Head


#declare GOLD_M = texture {
gold2 
}

#declare GRAY_M = texture {
color DimGray 
ambient 0.4
diffuse 1
reflection 0.3
phong 1.0
phong_size 20
brilliance 8
0.07
metallic
}

#declare BLUE_M = texture {
color CadetBlue 
ambient 0.28
diffuse 1
reflection 0.3
phong 1.0
phong_size 20
brilliance 8
0.07
metallic
}

#declare GLASS = 
texture {
  color Clear
  ambient 0.1
  diffuse 0.0
  reflection 0.2
  refraction 1.0
  ior 1.5
  phong 0.3
  phong_size 90
}














