//
// PDB2POV (UNIX) atom input prepared by pdb2pov 09/04/96 08:15:22
// Author: Eric G. Suchanek, Ph.D. 
// Mac port: Richard G. Rothwell, Ph.D. 
//	Atoms:   78 
//	Extent:	Xmin: -11.046 Xmax: 12.341, 
//		Ymin: -6.215, Ymax: 7.409
//		Zmin: -5.364 Zmax: 5.963 
//	Enclosing Sphere: 12.723

#declare BOND_RADIUS = 0.17 
#declare ATM_SCL = 1.0

//
// CPK version
//
#declare dihydrochlam_cpk_obj = union {
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.256, -1.669, 1.606> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.713, -1.989, 1.622> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.048, -3.210, 0.758> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.103, -2.259, 3.054> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.461, -0.722, 1.128> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.192, -0.098, 1.851> }
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.191, -0.357, -0.161> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.466, 0.975, -0.716> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.167, 0.910, -2.050> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-5.534, 0.253, -1.979> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-6.664, 1.008, -1.694> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-5.678, -1.080, -2.205> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-7.884, 0.397, -1.584> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-6.924, -1.700, -2.136> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-8.008, -0.981, -1.848> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.069, 1.619, -0.804> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.344, 1.290, -1.760> }
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.644, 2.383, 0.196> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.215, 2.766, 0.313> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.285, 4.048, 1.143> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.493, 3.883, 2.005> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.427, 2.957, 1.304> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.503, 1.617, 0.994> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.862, 1.679, 2.166> }
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.685, 0.510, 0.242> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.884, -0.828, 0.803> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <2.071, -1.565, 0.209> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <3.358, -0.765, 0.314> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <4.604, -1.532, -0.042> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <5.842, -0.614, -0.079> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.162, -1.358, -0.199> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.338, -0.366, -0.152> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <9.550, -0.963, 0.340> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.557, 0.232, -1.500> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.911, 1.506, -1.916> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <9.343, 1.440, -1.574> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.460, -1.523, 0.550> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.789, -1.789, -0.622> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.928, -1.836, 2.233> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.905, -2.753, -0.044> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.026, -3.404, 0.809> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.785, -3.715, 1.181> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.986, -1.681, 3.463> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.663, -2.872, 3.269> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.088, -2.349, 3.141> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.731, -0.888, -0.646> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.956, 1.283, -0.052> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.564, 0.414, -2.825> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.323, 1.616, -2.864> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-6.425, 2.112, -1.747> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.749, -1.667, -2.165> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-8.484, 0.825, -1.626> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-7.040, -2.679, -2.280> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-8.546, -1.847, -1.932> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.168, 2.899, -0.523> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.065, 4.909, 0.823> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.514, 4.114, 1.670> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.170, 4.632, 2.213> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.181, 3.469, 2.887> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.835, 2.103, 1.831> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.419, 3.427, 1.133> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.357, 0.623, -0.599> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <1.052, -0.727, 1.754> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <1.882, -1.636, -0.672> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <2.093, -2.392, 0.580> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <3.336, -0.056, -0.347> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <3.358, -0.214, 1.122> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <4.445, -1.945, -1.071> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <4.767, -2.218, 0.572> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <5.813, 0.105, 0.647> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <5.763, 0.003, -1.018> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.069, -1.976, 0.527> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.136, -1.906, -1.082> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.135, 0.319, 0.519> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <9.841, -1.601, -0.257> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.730, -0.580, -2.294> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.126, 1.893, -2.770> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.496, 2.091, -1.132> }
}

//
// BS version 
//
#declare BOND_RADIUS = 0.17 
#declare ATM_SCL = 0.25 

#declare dihydrochlam_obj = union {
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.256, -1.669, 1.606> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.713, -1.989, 1.622> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.048, -3.210, 0.758> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.103, -2.259, 3.054> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.461, -0.722, 1.128> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.192, -0.098, 1.851> }
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.191, -0.357, -0.161> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.466, 0.975, -0.716> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.167, 0.910, -2.050> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-5.534, 0.253, -1.979> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-6.664, 1.008, -1.694> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-5.678, -1.080, -2.205> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-7.884, 0.397, -1.584> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-6.924, -1.700, -2.136> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-8.008, -0.981, -1.848> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.069, 1.619, -0.804> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.344, 1.290, -1.760> }
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.644, 2.383, 0.196> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.215, 2.766, 0.313> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.285, 4.048, 1.143> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.493, 3.883, 2.005> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.427, 2.957, 1.304> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.503, 1.617, 0.994> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.862, 1.679, 2.166> }
object {Atom_N scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.685, 0.510, 0.242> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.884, -0.828, 0.803> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <2.071, -1.565, 0.209> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <3.358, -0.765, 0.314> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <4.604, -1.532, -0.042> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <5.842, -0.614, -0.079> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.162, -1.358, -0.199> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.338, -0.366, -0.152> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <9.550, -0.963, 0.340> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.557, 0.232, -1.500> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.911, 1.506, -1.916> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <9.343, 1.440, -1.574> }
object {Atom_C scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.460, -1.523, 0.550> }
object {Atom_O scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.789, -1.789, -0.622> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-0.928, -1.836, 2.233> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.905, -2.753, -0.044> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.026, -3.404, 0.809> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.785, -3.715, 1.181> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.986, -1.681, 3.463> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.663, -2.872, 3.269> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.088, -2.349, 3.141> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.731, -0.888, -0.646> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.956, 1.283, -0.052> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.564, 0.414, -2.825> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.323, 1.616, -2.864> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-6.425, 2.112, -1.747> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-4.749, -1.667, -2.165> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-8.484, 0.825, -1.626> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-7.040, -2.679, -2.280> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-8.546, -1.847, -1.932> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.168, 2.899, -0.523> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.065, 4.909, 0.823> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.514, 4.114, 1.670> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.170, 4.632, 2.213> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-1.181, 3.469, 2.887> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-2.835, 2.103, 1.831> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <-3.419, 3.427, 1.133> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <0.357, 0.623, -0.599> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <1.052, -0.727, 1.754> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <1.882, -1.636, -0.672> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <2.093, -2.392, 0.580> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <3.336, -0.056, -0.347> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <3.358, -0.214, 1.122> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <4.445, -1.945, -1.071> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <4.767, -2.218, 0.572> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <5.813, 0.105, 0.647> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <5.763, 0.003, -1.018> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.069, -1.976, 0.527> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.136, -1.906, -1.082> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.135, 0.319, 0.519> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <9.841, -1.601, -0.257> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.730, -0.580, -2.294> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <8.126, 1.893, -2.770> }
object {Atom_H scale <ATM_SCL, ATM_SCL, ATM_SCL> translate <7.496, 2.091, -1.132> }
cylinder { <9.34, 1.44, -1.57>, <7.50, 2.09, -1.13>, BOND_RADIUS texture {White_Bond} } 
cylinder { <9.34, 1.44, -1.57>, <8.13, 1.89, -2.77>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.56, 0.23, -1.50>, <8.73, -0.58, -2.29>, BOND_RADIUS texture {White_Bond} } 
cylinder { <9.55, -0.96, 0.34>, <9.84, -1.60, -0.26>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.56, 0.23, -1.50>, <8.14, 0.32, 0.52>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.34, -0.37, -0.15>, <7.14, -1.91, -1.08>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.34, -0.37, -0.15>, <7.07, -1.98, 0.53>, BOND_RADIUS texture {White_Bond} } 
cylinder { <7.16, -1.36, -0.20>, <5.76, 0.00, -1.02>, BOND_RADIUS texture {White_Bond} } 
cylinder { <7.16, -1.36, -0.20>, <5.81, 0.11, 0.65>, BOND_RADIUS texture {White_Bond} } 
cylinder { <5.84, -0.61, -0.08>, <4.77, -2.22, 0.57>, BOND_RADIUS texture {White_Bond} } 
cylinder { <5.84, -0.61, -0.08>, <4.45, -1.95, -1.07>, BOND_RADIUS texture {White_Bond} } 
cylinder { <4.60, -1.53, -0.04>, <3.36, -0.21, 1.12>, BOND_RADIUS texture {White_Bond} } 
cylinder { <4.60, -1.53, -0.04>, <3.34, -0.06, -0.35>, BOND_RADIUS texture {White_Bond} } 
cylinder { <3.36, -0.77, 0.31>, <2.09, -2.39, 0.58>, BOND_RADIUS texture {White_Bond} } 
cylinder { <3.36, -0.77, 0.31>, <1.88, -1.64, -0.67>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.46, -1.52, 0.55>, <1.05, -0.73, 1.75>, BOND_RADIUS texture {White_Bond} } 
cylinder { <0.88, -0.83, 0.80>, <0.36, 0.62, -0.60>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-2.43, 2.96, 1.30>, <-3.42, 3.43, 1.13>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-2.43, 2.96, 1.30>, <-2.83, 2.10, 1.83>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-2.43, 2.96, 1.30>, <-1.18, 3.47, 2.89>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-2.43, 2.96, 1.30>, <-2.17, 4.63, 2.21>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-1.49, 3.88, 2.00>, <0.51, 4.11, 1.67>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.28, 4.05, 1.14>, <0.07, 4.91, 0.82>, BOND_RADIUS texture {White_Bond} } 
cylinder { <0.50, 1.62, 0.99>, <0.17, 2.90, -0.52>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-8.01, -0.98, -1.85>, <-8.55, -1.85, -1.93>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-8.01, -0.98, -1.85>, <-7.04, -2.68, -2.28>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-8.01, -0.98, -1.85>, <-8.48, 0.82, -1.63>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-6.92, -1.70, -2.14>, <-4.75, -1.67, -2.17>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-6.66, 1.01, -1.69>, <-6.42, 2.11, -1.75>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.53, 0.25, -1.98>, <-4.32, 1.62, -2.86>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.53, 0.25, -1.98>, <-3.56, 0.41, -2.83>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-2.07, 1.62, -0.80>, <-3.96, 1.28, -0.05>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.79, -1.79, -0.62>, <-2.73, -0.89, -0.65>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.10, -2.26, 3.05>, <-4.09, -2.35, 3.14>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.10, -2.26, 3.05>, <-2.66, -2.87, 3.27>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.10, -2.26, 3.05>, <-2.99, -1.68, 3.46>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.05, -3.21, 0.76>, <-2.78, -3.71, 1.18>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.05, -3.21, 0.76>, <-4.03, -3.40, 0.81>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.05, -3.21, 0.76>, <-2.90, -2.75, -0.04>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.46, -1.52, 0.55>, <-0.93, -1.84, 2.23>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.46, -1.52, 0.55>, <-0.79, -1.79, -0.62>, BOND_RADIUS texture {White_Bond} } 
cylinder { <0.88, -0.83, 0.80>, <-0.46, -1.52, 0.55>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-1.26, -1.67, 1.61>, <-0.46, -1.52, 0.55>, BOND_RADIUS texture {White_Bond} } 
cylinder { <7.91, 1.51, -1.92>, <9.34, 1.44, -1.57>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.56, 0.23, -1.50>, <9.34, 1.44, -1.57>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.56, 0.23, -1.50>, <7.91, 1.51, -1.92>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.34, -0.37, -0.15>, <8.56, 0.23, -1.50>, BOND_RADIUS texture {White_Bond} } 
cylinder { <8.34, -0.37, -0.15>, <9.55, -0.96, 0.34>, BOND_RADIUS texture {White_Bond} } 
cylinder { <7.16, -1.36, -0.20>, <8.34, -0.37, -0.15>, BOND_RADIUS texture {White_Bond} } 
cylinder { <5.84, -0.61, -0.08>, <7.16, -1.36, -0.20>, BOND_RADIUS texture {White_Bond} } 
cylinder { <4.60, -1.53, -0.04>, <5.84, -0.61, -0.08>, BOND_RADIUS texture {White_Bond} } 
cylinder { <3.36, -0.77, 0.31>, <4.60, -1.53, -0.04>, BOND_RADIUS texture {White_Bond} } 
cylinder { <2.07, -1.56, 0.21>, <3.36, -0.77, 0.31>, BOND_RADIUS texture {White_Bond} } 
cylinder { <0.88, -0.83, 0.80>, <2.07, -1.56, 0.21>, BOND_RADIUS texture {White_Bond} } 
cylinder { <0.69, 0.51, 0.24>, <0.88, -0.83, 0.80>, BOND_RADIUS texture {White_Bond} } 
cylinder { <0.50, 1.62, 0.99>, <0.69, 0.51, 0.24>, BOND_RADIUS texture {White_Bond} } 
cylinder { <0.50, 1.62, 0.99>, <0.86, 1.68, 2.17>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.21, 2.77, 0.31>, <0.50, 1.62, 0.99>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-1.49, 3.88, 2.00>, <-2.43, 2.96, 1.30>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-1.64, 2.38, 0.20>, <-2.43, 2.96, 1.30>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.28, 4.05, 1.14>, <-1.49, 3.88, 2.00>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-0.21, 2.77, 0.31>, <-0.28, 4.05, 1.14>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-1.64, 2.38, 0.20>, <-0.21, 2.77, 0.31>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-2.07, 1.62, -0.80>, <-1.64, 2.38, 0.20>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-2.07, 1.62, -0.80>, <-1.34, 1.29, -1.76>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.47, 0.97, -0.72>, <-2.07, 1.62, -0.80>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-6.92, -1.70, -2.14>, <-8.01, -0.98, -1.85>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-7.88, 0.40, -1.58>, <-8.01, -0.98, -1.85>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.68, -1.08, -2.21>, <-6.92, -1.70, -2.14>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-6.66, 1.01, -1.69>, <-7.88, 0.40, -1.58>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.53, 0.25, -1.98>, <-5.68, -1.08, -2.21>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-5.53, 0.25, -1.98>, <-6.66, 1.01, -1.69>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-4.17, 0.91, -2.05>, <-5.53, 0.25, -1.98>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.47, 0.97, -0.72>, <-4.17, 0.91, -2.05>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.19, -0.36, -0.16>, <-3.47, 0.97, -0.72>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.46, -0.72, 1.13>, <-3.19, -0.36, -0.16>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-3.46, -0.72, 1.13>, <-4.19, -0.10, 1.85>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-2.71, -1.99, 1.62>, <-3.46, -0.72, 1.13>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-2.71, -1.99, 1.62>, <-3.10, -2.26, 3.05>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-2.71, -1.99, 1.62>, <-3.05, -3.21, 0.76>, BOND_RADIUS texture {White_Bond} } 
cylinder { <-1.26, -1.67, 1.61>, <-2.71, -1.99, 1.62>, BOND_RADIUS texture {White_Bond} } 
}

#declare dihydrochlam = object {
	object { dihydrochlam_obj } 
	rotate <45, 0, 90>
	translate <0, 9.5, -8>
     } 

#declare dihydrochlam_cpk = object {
	object { dihydrochlam_cpk_obj } 
	rotate <180, 0, 90>
	translate <0, 9.5, -8>
     } 


