//
// preset aspect ratios for convenient rendering to different output media
//

#declare PC_ASPECT = 1.33333    // typical PC screen
#declare PC_ASPECT_PORTRAIT = 0.75 // e.g. 240x320
#declare HDTV =      1.77778    // HDTV format
#declare FOURBYFIVE = .8        // good for 8"x10" or multiples for paper, portrait
#declare EIGHTBYTEN = .8
#declare TENBYEIGHT = 1.25
#declare FIVEBYFOUR = 1.25      // good for 8"x10" or multiples for paper, landscape
#declare POSTER24x36 = 0.66667  // 24x36" standard poster size
#declare POSTER36x48 = 0.75     // 36x48"
#declare POSTER36x24 = 1.5      // 36x24" portrait poster
#declare POSTER48x36 = 1.33333



